apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "helm-charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "helm-charts.selectorLabels" . | nindent 8 }}  
    spec:
      containers:
      - name: {{ .Values.container.name }}
        securityContext:
            allowPrivilegeEscalation: false
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
#        livenessProbe:
#          exec:
#            command:
#              - cat
#              - /tmp/healthy
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
        readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
        resources:
            requests:
              memory: 0.25Gi
              cpu: 0.5
            limits:
              memory: 0.25Gi 
              cpu: 0.5
        volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.persistentvolume.hostpath }}
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
              claimName: {{ .Release.Name }}-pvc