apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  storageClassName: {{ .Values.persistentvolume.storageclass }}
  accessModes:
    - {{ .Values.persistentvolume.accessmode }}
  resources:
    requests:
      storage: {{ .Values.persistentvolume.storage }}